/*点击middle2七个按钮触发按钮，图片，文字改变*/
function test1(){
	if(document.getElementById('id1').className=='table'){
		document.getElementById('id1').className='table-onclick';
		document.getElementById('id2').className='table';
		document.getElementById('id3').className='table';
		document.getElementById('id4').className='table';
		document.getElementById('id5').className='table';
		document.getElementById('id6').className='table';
		document.getElementById('id7').className='table';
		document.getElementById('img-mid').src='static/img/middle2-img.jpg';
		document.getElementById('text').innerText='用户不但可以通过浏览供应商品列表、采购需求列表，获取当下热销的商品信息。也可以通过“搜索”、“二维码扫描”、“语音识别”功能按钮进行定向商品信息检索。';
	}
}
function test2(){
	if(document.getElementById('id2').className=='table'){
		document.getElementById('id2').className='table-onclick';
		document.getElementById('id1').className='table';
		document.getElementById('id3').className='table';
		document.getElementById('id4').className='table';
		document.getElementById('id5').className='table';
		document.getElementById('id6').className='table';
		document.getElementById('id7').className='table';
		document.getElementById('img-mid').src='static/img/middle2-img2.jpg';
		document.getElementById('text').innerText='用户可以对当下的行情信息进行全面的了解。用户可以首先通过“行情品类”下各个子按钮进行商品品类的选择，了解相关的供应报价和采购定价信息。也可以在此页面自行发布相关信息，以获取商业机会。';
	}
}function test3(){
	if(document.getElementById('id3').className=='table'){
		document.getElementById('id3').className='table-onclick';
		document.getElementById('id2').className='table';
		document.getElementById('id1').className='table';
		document.getElementById('id4').className='table';
		document.getElementById('id5').className='table';
		document.getElementById('id6').className='table';
		document.getElementById('id7').className='table';
		document.getElementById('img-mid').src='static/img/middle2-img3.jpg';
		document.getElementById('text').innerText='用户可以对自己的总资产及当期收益有直观了解。同时也可以查看所投资产品的类目及详情。该页面同时提供热门投资产品的推送服务，方便用户选购。';
	}
}function test4(){
	if(document.getElementById('id4').className=='table'){
		document.getElementById('id4').className='table-onclick';
		document.getElementById('id2').className='table';
		document.getElementById('id3').className='table';
		document.getElementById('id1').className='table';
		document.getElementById('id5').className='table';
		document.getElementById('id6').className='table';
		document.getElementById('id7').className='table';
		document.getElementById('img-mid').src='static/img/middle2-img4.jpg';
		document.getElementById('text').innerText='用户不但可以通过浏览供应商品列表、采购需求列表，获取当下热销的商品信息。也可以通用户可以了解自己的信用额度以及当期应还款金额。同时也提供了市场上热门的借贷产品类目以满足不同用户的需求，提供最方便快捷的融资渠道。';
	}
}function test5(){
	if(document.getElementById('id5').className=='table'){
		document.getElementById('id5').className='table-onclick';
		document.getElementById('id2').className='table';
		document.getElementById('id3').className='table';
		document.getElementById('id4').className='table';
		document.getElementById('id1').className='table';
		document.getElementById('id6').className='table';
		document.getElementById('id7').className='table';
		document.getElementById('img-mid').src='static/img/middle2-img5.jpg';
		document.getElementById('text').innerText='用户可以了解自己的总保额以及当期投保详情，同时丰富的保险产品类目也为用户提供多样化的投保选择。';
	}
}function test6(){
	if(document.getElementById('id6').className=='table'){
		document.getElementById('id6').className='table-onclick';
		document.getElementById('id2').className='table';
		document.getElementById('id3').className='table';
		document.getElementById('id4').className='table';
		document.getElementById('id5').className='table';
		document.getElementById('id1').className='table';
		document.getElementById('id7').className='table';
		document.getElementById('img-mid').src='static/img/middle2-img6.jpg';
		document.getElementById('text').innerText='通过添加好友至“通讯录”的方式建立自己的的社交圈，不但提供了“单聊”或“群聊”的方式进行日常沟通交流，也可以以文字和视频的形式自行发布动态，通过“评论”、“关注”、“转发”的方式与好友进行亲密互动，同时也增加了自己的影响力。此外，基于智能文字识别技术，实现利用聊天记录直接生成商业合同的功能，缩短用户的签约时间。';
	}
}function test7(){
	if(document.getElementById('id7').className=='table'){
		document.getElementById('id7').className='table-onclick';
		document.getElementById('id2').className='table';
		document.getElementById('id3').className='table';
		document.getElementById('id4').className='table';
		document.getElementById('id5').className='table';
		document.getElementById('id6').className='table';
		document.getElementById('id1').className='table';
	}
}